# Generated by Django 3.0.4 on 2020-04-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecomment',
            name='EID',
        ),
    ]
