# Generated by Django 3.0.4 on 2020-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20200418_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='time',
            field=models.DateField(),
        ),
    ]
