# Generated by Django 3.0.4 on 2020-04-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_casecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
