# Generated by Django 3.0.4 on 2020-04-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20200420_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
