# Generated by Django 3.0.4 on 2020-04-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_auto_20200420_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='rname',
        ),
    ]
