# Generated by Django 3.0.4 on 2020-04-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_remove_resolution_rname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='rid',
        ),
        migrations.AddField(
            model_name='check',
            name='ProductNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.product'),
            preserve_default=False,
        ),
    ]
