# Generated by Django 3.0.4 on 2020-04-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20200422_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='CaseNo',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
